encoder_embed_path: null
encoder_embed_dim: 1024
encoder_ffn_embed_dim: 2048
encoder_layers: 3
encoder_attention_heads: 8
encoder_normalize_before: False
encoder_learned_pos: False
decoder_embed_path: null
decoder_embed_dim: 1024
decoder_ffn_embed_dim: 2048
decoder_layers: 3
decoder_attention_heads: 8
decoder_normalize_before: False
decoder_learned_pos: False
decoder_layerdrop: 0
attention_dropout: 0.0
activation_dropout: 0.0
activation_fn: "relu"
dropout: 0.1
adaptive_softmax_cutoff: null
adaptive_softmax_dropout: 0
share_decoder_input_output_embed: False
share_all_embeddings: False
no_token_positional_embeddings: False
adaptive_input: False
no_cross_attention: False
cross_self_attention: False
decoder_output_dim: 512
decoder_input_dim: 512
no_scale_embedding: False
layernorm_embedding: False
tie_adaptive_weights: False