video_trimmed_dir: "./data/vsitu_video_trimmed_dir"
video_frm_tdir: "./data/vsitu_video_frames_dir"
max_processes: 30
split_dir: "./data/vidsitu_annotations/split_files"
cookies_file: ''
retry_count: 3
hard_check: false
suppress_ffmpeg_outputs: false